# Auto-generated by TL2b
import os, random

# Tune via env:
#   TRUMP_MAX_RANTS  -> max trailing rants per print (default: 2 normal, 5 press)
#   TRUMP_RANT_RATE  -> probability (0..1) we add *another* rant after a print (default: 0.35)
#   TRUMPSEED        -> seed RNG for reproducible output (optional)

if (seed := os.environ.get("TRUMPSEED")):
    try: random.seed(int(seed))
    except Exception: random.seed(seed)

POSITIVE = [
    "Total respect. It’s beautiful.",
    "Incredible. People are saying it’s the best.",
    "Tremendous result. Everyone agrees.",
    "So strong. Very strong.",
    "Historic. Never been done before.",
    "We’re doing numbers, big numbers.",
    "People can’t believe how good it is.",
    "World‑class. The best anywhere.",
    "They said it couldn’t be done—done.",
    "Winning like you wouldn’t believe."
]

NEGATIVE = [
    "Sad! Nobody’s ever seen anything like it.",
    "Disaster. We inherited this.",
    "Very unfair. Everyone knows it.",
    "Total witch hunt against math.",
    "Crooked situation. Not good.",
    "Rigged from day one. Frankly.",
    "A lot of problems—terrible problems.",
    "We’re looking into it. Not pretty.",
    "Could have been prevented. Not by me.",
    "Embarrassing. People are talking."
]

PRESS_MONOLOGUES = [
    "A lot of people don’t understand this, but it’s very technical.",
    "Look, folks, I didn’t build it, but I know how it works. Trust me.",
    "We’re looking into it. There may have been interference.",
    "Nobody could’ve seen this coming, but we handled it better than anyone.",
    "Some people say it’s the worst error ever—people are saying.",
    "We’ve got tremendous experts. The best people.",
    "This would’ve never happened under my administration.",
    "We inherited a mess, but we’re doing numbers now—big numbers.",
    "We found the bug. It was hiding. Nobody else could’ve found it.",
    "Don’t worry, we’re going to fix it. Fast. Very fast."
]

def pick_rants(max_n: int, positive_bias=True):
    """Return a list of 0..max_n rants, geometrically capped by TRUMP_RANT_RATE."""
    try:
        rate = float(os.environ.get("TRUMP_RANT_RATE", "0.35"))
    except Exception:
        rate = 0.35
    n = 0
    rants = []
    # draw at least 0; keep flipping with probability=rate until we stop or hit max_n
    while n < max_n and random.random() < rate:
        pool = POSITIVE if positive_bias else NEGATIVE
        rants.append(random.choice(pool))
        n += 1
    return rants
