# Auto-generated by TL2b
import os, sys, traceback, random
from .trumplang_rants import PRESS_MONOLOGUES, pick_rants

def press_excepthook(exc_type, exc, tb):
    sys.stderr.write("🚨 Something happened, folks.\n")
    sys.stderr.write(">>> " + random.choice(PRESS_MONOLOGUES) + "\n")
    # In press mode, allow up to 5 bonus rants by default
    max_rants = int(os.environ.get("TRUMP_MAX_RANTS", "5"))
    for riff in pick_rants(max_rants=max_rants, positive_bias=False):
        sys.stderr.write("— " + riff + "\n")
    # Show a compact technical bit at the end
    last = traceback.extract_tb(tb)[-1] if tb else None
    if last:
        sys.stderr.write(f"📍 {last.filename}:{last.lineno} in {last.name}\n")
    sys.stderr.write(f"{exc_type.__name__}: {exc}\n")

def enable():
    sys.excepthook = press_excepthook
