#!/usr/bin/env python3
from pathlib import Path
import shutil

root = Path(__file__).resolve().parents[1]

def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        bak = path.with_suffix(path.suffix + ".bak_TL2b")
        if not bak.exists():
            shutil.copy2(path, bak)
    path.write_text(text, encoding="utf-8")
    print(("Updated" if path.exists() else "Added"), path)

rhetoric = r'''# Auto-generated by TL2b
import os, random

# Controls:
#   TRUMP_MAX_RANTS: int cap per event (default 2 normal, 5 press)
#   TRUMP_RANT_RATE: 0..1 per-rant continuation probability (default 0.35)
#   TRUMPSEED      : RNG seed for reproducibility (optional)

if (seed := os.environ.get("TRUMPSEED")):
    try: random.seed(int(seed))
    except Exception: random.seed(seed)

POSITIVE = [
    "Total respect. It’s beautiful.",
    "Incredible. People are saying it’s the best.",
    "Tremendous result. Everyone agrees.",
    "So strong. Very strong.",
    "Historic. Never been done before.",
    "We’re doing numbers—big numbers.",
    "People can’t believe how good it is.",
    "World‑class. The best anywhere.",
    "They said it couldn’t be done—done.",
    "Winning like you wouldn’t believe.",
    "Legendary performance. Off the charts.",
    "Unbelievable. They’re calling it perfect.",
    "We love to see it. Everybody loves it.",
    "Exactly as predicted. Nailed it.",
    "Picture‑perfect. Couldn’t be better.",
]

NEGATIVE = [
    "Sad! Nobody’s ever seen anything like it.",
    "Disaster. We inherited this.",
    "Very unfair. Everyone knows it.",
    "Total witch hunt against math.",
    "Crooked situation. Not good.",
    "Rigged from day one. Frankly.",
    "A lot of problems—terrible problems.",
    "We’re looking into it. Not pretty.",
    "Could have been prevented. Not by me.",
    "Embarrassing. People are talking.",
    "Out of control. A complete mess.",
    "Not what we wanted. Believe me.",
    "They botched it. Everyone says so.",
    "We’ll fix it—fast. But wow.",
    "Should never happen again. Ever.",
]

PRESS_MONOLOGUES = [
    "A lot of people don’t understand this, but it’s very technical.",
    "Look, folks, I didn’t build it, but I know how it works. Trust me.",
    "We’re looking into it. There may have been interference.",
    "Nobody could’ve seen this coming, but we handled it better than anyone.",
    "Some people say it’s the worst error ever—people are saying.",
    "We’ve got tremendous experts. The best people.",
    "This would’ve never happened under my administration.",
    "We inherited a mess, but we’re doing numbers now—big numbers.",
    "We found the bug. It was hiding. Nobody else could’ve found it.",
    "Don’t worry, we’re going to fix it. Fast. Very fast.",
]

def _rate():
    try: return max(0.0, min(1.0, float(os.environ.get("TRUMP_RANT_RATE", "0.35"))))
    except Exception: return 0.35

def pick_rants(max_n: int, positive_bias: bool) -> list[str]:
    """Geometric-tail selector: keep adding with probability = TRUMP_RANT_RATE, capped by max_n."""
    pool = POSITIVE if positive_bias else NEGATIVE
    out, n = [], 0
    rate = _rate()
    # Try the first rant with the same probability as subsequent ones; yields 0..max_n items.
    while n < max_n and random.random() < rate:
        out.append(random.choice(pool))
        n += 1
    return out
'''

bootstrap = r'''# Auto-generated by TL2b
import os, sys, builtins, traceback, random
from .trumplang_rhetoric import pick_rants, PRESS_MONOLOGUES

def _mode():
    m = (os.environ.get("TRUMPMODE") or "").strip().lower()
    if not m:
        for x in getattr(sys, "_xoptions", ()):
            if x.lower().startswith("trumplang="):
                m = x.split("=",1)[1].strip().lower()
                break
    return m

def _max(default_normal: int) -> int:
    try: return int(os.environ.get("TRUMP_MAX_RANTS", str(default_normal)))
    except Exception: return default_normal

def _wrap_print(max_rants: int, positive_bias: bool):
    old_print = builtins.print
    def trump_print(*args, **kwargs):
        old_print(*args, **kwargs)
        for riff in pick_rants(max_n=max_rants, positive_bias=positive_bias):
            old_print(riff)
    builtins.print = trump_print

def _press_excepthook(exc_type, exc, tb):
    sys.stderr.write("🚨 Something happened, folks.\n")
    sys.stderr.write(">>> " + random.choice(PRESS_MONOLOGUES) + "\n")
    # In press mode we allow up to 5 negative riffs by default
    cap = _max(default_normal=5)
    for riff in pick_rants(max_n=cap, positive_bias=False):
        sys.stderr.write("— " + riff + "\n")
    last = traceback.extract_tb(tb)[-1] if tb else None
    if last:
        sys.stderr.write(f"📍 {last.filename}:{last.lineno} in {last.name}\n")
    sys.stderr.write(f"{exc_type.__name__}: {exc}\n")

def _install():
    m = _mode()
    if m in ("press", "press-conference", "pc"):
        _wrap_print(_max(default_normal=5), positive_bias=True)  # chattier prints in press mode
        sys.excepthook = _press_excepthook
    elif m in ("rant", "rants"):
        _wrap_print(_max(default_normal=2), positive_bias=True)
    # else off

_install()
'''

write(root / "Lib" / "trumplang_rhetoric.py", rhetoric)
write(root / "Lib" / "trumplang_bootstrap.py", bootstrap)
print("Done. (If site.py hook not installed yet, re-run the earlier TL2a site hook patch.)")
