#!/usr/bin/env python3
from pathlib import Path
import shutil

root = Path(__file__).resolve().parents[1]

def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(text, encoding="utf-8")
        print(f"Added {path}")
    else:
        # always overwrite for now (easier iteration)
        bak = path.with_suffix(path.suffix + ".bak_TL2b")
        if not bak.exists():
            shutil.copy2(path, bak)
        path.write_text(text, encoding="utf-8")
        print(f"Updated {path}")

# --- Lib/trumplang_rants.py ---------------------------------------------------
trumplang_rants = r'''# Auto-generated by TL2b
import os, random

# Tune via env:
#   TRUMP_MAX_RANTS  -> max trailing rants per print (default: 2 normal, 5 press)
#   TRUMP_RANT_RATE  -> probability (0..1) we add *another* rant after a print (default: 0.35)
#   TRUMPSEED        -> seed RNG for reproducible output (optional)

if (seed := os.environ.get("TRUMPSEED")):
    try: random.seed(int(seed))
    except Exception: random.seed(seed)

POSITIVE = [
    "Total respect. It’s beautiful.",
    "Incredible. People are saying it’s the best.",
    "Tremendous result. Everyone agrees.",
    "So strong. Very strong.",
    "Historic. Never been done before.",
    "We’re doing numbers, big numbers.",
    "People can’t believe how good it is.",
    "World‑class. The best anywhere.",
    "They said it couldn’t be done—done.",
    "Winning like you wouldn’t believe."
]

NEGATIVE = [
    "Sad! Nobody’s ever seen anything like it.",
    "Disaster. We inherited this.",
    "Very unfair. Everyone knows it.",
    "Total witch hunt against math.",
    "Crooked situation. Not good.",
    "Rigged from day one. Frankly.",
    "A lot of problems—terrible problems.",
    "We’re looking into it. Not pretty.",
    "Could have been prevented. Not by me.",
    "Embarrassing. People are talking."
]

PRESS_MONOLOGUES = [
    "A lot of people don’t understand this, but it’s very technical.",
    "Look, folks, I didn’t build it, but I know how it works. Trust me.",
    "We’re looking into it. There may have been interference.",
    "Nobody could’ve seen this coming, but we handled it better than anyone.",
    "Some people say it’s the worst error ever—people are saying.",
    "We’ve got tremendous experts. The best people.",
    "This would’ve never happened under my administration.",
    "We inherited a mess, but we’re doing numbers now—big numbers.",
    "We found the bug. It was hiding. Nobody else could’ve found it.",
    "Don’t worry, we’re going to fix it. Fast. Very fast."
]

def pick_rants(max_n: int, positive_bias=True):
    """Return a list of 0..max_n rants, geometrically capped by TRUMP_RANT_RATE."""
    try:
        rate = float(os.environ.get("TRUMP_RANT_RATE", "0.35"))
    except Exception:
        rate = 0.35
    n = 0
    rants = []
    # draw at least 0; keep flipping with probability=rate until we stop or hit max_n
    while n < max_n and random.random() < rate:
        pool = POSITIVE if positive_bias else NEGATIVE
        rants.append(random.choice(pool))
        n += 1
    return rants
'''

# --- Lib/trumplang_press.py ---------------------------------------------------
trumplang_press = r'''# Auto-generated by TL2b
import os, sys, traceback, random
from .trumplang_rants import PRESS_MONOLOGUES, pick_rants

def press_excepthook(exc_type, exc, tb):
    sys.stderr.write("🚨 Something happened, folks.\n")
    sys.stderr.write(">>> " + random.choice(PRESS_MONOLOGUES) + "\n")
    # In press mode, allow up to 5 bonus rants by default
    max_rants = int(os.environ.get("TRUMP_MAX_RANTS", "5"))
    for riff in pick_rants(max_rants=max_rants, positive_bias=False):
        sys.stderr.write("— " + riff + "\n")
    # Show a compact technical bit at the end
    last = traceback.extract_tb(tb)[-1] if tb else None
    if last:
        sys.stderr.write(f"📍 {last.filename}:{last.lineno} in {last.name}\n")
    sys.stderr.write(f"{exc_type.__name__}: {exc}\n")

def enable():
    sys.excepthook = press_excepthook
'''

# --- Lib/trumplang_bootstrap.py ----------------------------------------------
bootstrap = r'''# Auto-generated by TL2b
import os, sys, builtins
from .trumplang_rants import pick_rants
from . import trumplang_press as _press

def _mode():
    # env first
    m = (os.environ.get("TRUMPMODE") or "").strip()
    if not m:
        # look at -X trumplang=...
        for x in getattr(sys, "_xoptions", ()):
            if x.lower().startswith("trumplang="):
                m = x.split("=", 1)[1]
                break
    return m.strip().lower()

def _max_rants(default_normal=2):
    try:
        return int(os.environ.get("TRUMP_MAX_RANTS", str(default_normal)))
    except Exception:
        return default_normal

def _install_rant_print(max_rants):
    old_print = builtins.print
    def trump_print(*args, **kwargs):
        old_print(*args, **kwargs)
        # append 0..max_rants positive riffs (geometric by TRUMP_RANT_RATE)
        for riff in pick_rants(max_n=max_rants, positive_bias=True):
            old_print(riff)
    builtins.print = trump_print

def _install_press():
    _press.enable()

def _install():
    m = _mode()
    if m in ("press", "press-conference", "pc"):
        _install_rant_print(_max_rants(default_normal=5))  # make it extra chatty in press mode
        _install_press()
    elif m in ("rant", "rants"):
        _install_rant_print(_max_rants(default_normal=2))
    # else: off

_install()
'''

write(root / "Lib" / "trumplang_rants.py", trumplang_rants)
write(root / "Lib" / "trumplang_press.py", trumplang_press)
write(root / "Lib" / "trumplang_bootstrap.py", bootstrap)
